r1:
  hostname: r1.cisco.com
  groups:
    - csr1000v
  data:
    GigabitEthernet1: 10.0.1.4
    asn: 66401
    neighbor_addr: 10.0.1.6
    neighbor_asn: 66801
    networks:
      - net: 10.12.0.0
        mask: 255.255.0.0
      - net: 10.16.0.0
        mask: 255.255.0.0
      - net: 10.192.25.0
        mask: 255.255.255.0

r2:
  hostname: r2.cisco.com
  groups:
    - csr1000v
  data:
    GigabitEthernet1: 10.0.1.6
    asn: 66801
    neighbor_addr: 10.0.1.4
    neighbor_asn: 66401
    networks:
      - net: 192.168.23.0
        mask: 255.255.255.0
      - net: 192.168.24.0
        mask: 255.255.255.0
      - net: 192.168.38.0
        mask: 255.255.255.0
